### ISSUE TITLE
License for the codes

### ISSUE THREAD

**Issue by wirawan0** [docker-32bit/ubuntu#16]
Hi folks,

Great work for making the 32-bit image preparation scripts available for us! I want to ask you to consider what you want to license your work on. Just so nobody can get tripped over this issue later on. I just adapted your work to generate my own 32-bit Trusty image, which is being used to run wine (and maybe later, skype). My host is 64-bit and I hate to pollute that with 32-bit packages, so this containerization is a great alternative.

Wirawan

**Comment by dashohoxha** [comment]
Which one do you thing is better, GPLv2 or GPLv3?
Anyway, it is such a small script that it can even be public domain (get it and do whatever you want).
What is your opinion?

**Comment by wirawan0** [comment]
Interesting, there is no response. To me any common open-source license (BSD, MIT, or GPL) is fine. I'd say, the authors need to speak up to voice their thought. Dashamir, are you the author of these tools (including prep script for other distros--debian, etc)?

**Comment by dashohoxha** [comment]
@wirawan0 there was no response from you, my question was to you.
It seems that I am the main author: https://github.com/docker-32bit/ubuntu/blame/master/build-image.sh
But I always copy/paste what I find in tutorials and tips on the internet, so most of it can be considered as "stolen" from somewhere else.
Anyway, since you think that GPL is fine, I am adding GPL.
