### ISSUE TITLE
support for more ubuntu versions

### ISSUE THREAD

**Issue by mcandre** [docker-32bit/ubuntu#3]
Could you please upload more 32bit ubuntu versions, such as raring and precise?

**Comment by dashohoxha** [comment]
Does this commit fix the problem: 846bd5853272bc2efd112b4b7d96bfe327d5a602
Or you meant something else?

**Comment by mcandre** [comment]
I mean something else. I'd love to see 32bit tags on DockerHub for older versions of ubuntu, like 32bit/ubuntu:13.04, 32bit/ubuntu:12.04, 32bit/ubuntu:11.04, etc.

**Comment by dashohoxha** [comment]
Do you really need them or you just think it would be nice? I think that only the latest and the previous one would be useful (that is 14.04 and 12.04). Releases 13.04 and 11.04 are not LTS, 10.04 is too old and maybe not supported anymore, and so on.
They don't need to be necessarily on DockerHub, since anybody can generate them from the scratch on his machine (where they will be used).

Anyway, if you are willing to generate ubuntu:12.04, push it on DockerHub as 'mcandre/ubuntu:12.04' and I will copy it to '32bit/ubuntu:12.04'.

**Comment by mcandre** [comment]
Thanks! I'll let you know when I get around to pushing them.

**Comment by mcandre** [comment]
I've pushed `debootstrap --arch i386`-generated base images for old Ubuntu and Debian versions:

https://registry.hub.docker.com/u/mcandre/docker-ubuntu-32bit/tags/manage/

https://registry.hub.docker.com/u/mcandre/docker-debian-32bit/tags/manage/

Let me know what you think!

**Comment by dashohoxha** [comment]
You have done a great work.
I have added you to: https://hub.docker.com/account/organizations/32bit/
I don't know exactly how these dockerhub organizations work, but I hope that you will be able to edit the repositories here: https://registry.hub.docker.com/repos/32bit/.

In my opinion it would be less confusing for people if all the images are in one place.
The same goes for the scripts/code: it would be better if you add your branches to https://github.com/docker-32bit/debian and https://github.com/docker-32bit/ubuntu (you don't have to change the master, just add branches for each version).
I have sent you an invitation and after accepting it I hope that you will have all the required permissions for doing this.

**Comment by dashohoxha** [comment]
By the way, I have noticed that you are building a lot of docker images, like this: https://github.com/mcandre/docker-ruby
Do you think that it would be useful to bring all these efforts in a common place like this: https://github.com/docker-build ?

**Comment by mcandre** [comment]
> it would be better if you add your branches to https://github.com/docker-32bit/debian and https://github.com/docker-32bit/ubuntu (you don't have to change the master, just add branches for each version).

Feel free to steal from my branches, I think we the build scripts have a slightly different workflow but nothing too serious. You'll note that some of the older debian OS's no longer have debootstrap scripts in modern debootstrap versions, so you have to boot an intermediate debian first. The truly ancient versions bo, rex, and buzz are only accessible via qemu for now.

Same goes for the ubuntu versions, feel free to steal build scripts from my branches!

Aw, thanks for forking some of my bases to docker-build!

**Comment by dashohoxha** [comment]
I can steal your branches, but the problem is that I don't want to duplicate your work. For example if you fix something on your repo, I would have to port it to this repo.
Another problem is that I am not using 32bit docker anymore, so I have lost the interest in maintaining 32bit scripts and images. If you still are interested in 32bit docker, then I could delegate this to you. Anyway, you seem to be much more familiar with Debian than I am.

My scripts are generic scripts, in the sense that they can be used to generate images for different versions of debian/ubuntu. Your branches are specific for each version of debian/ubuntu. I think that they can co-exist in the same git repository.

**Comment by mcandre** [comment]
Yeah, I get the sense that the 32bit and mcandre/docker-...-32bit repos
have different workflows, which is fine.

I love generalism, but the more recent versions of debootstrap deleted
scripts for building the older debian OS's, and different versions of
aptitude use different syntaxes. It's like we need to build *yet another
wrapper* to properly build these chroots.

I'm not that knowledgeable about Debian, I just poke around in edge cases
that most people never touch, like needing slink in 2015.

On Fri, May 29, 2015 at 12:53 AM, Dashamir Hoxha <notifications@github.com>
wrote:

> I can steal your branches, but the problem is that I don't want to
> duplicate your work. For example if you fix something on your repo, I would
> have to port it to this repo.
> Another problem is that I am not using 32bit docker anymore, so I have
> lost the interest in maintaining 32bit scripts and images. If you still are
> interested in 32bit docker, then I could delegate this to you. Anyway, you
> seem to be much more familiar with Debian than I am.
>
> My scripts are generic scripts, in the sense that they can be used to
> generate images for different versions of debian/ubuntu. Your branches are
> specific for each version of debian/ubuntu. I think that they can co-exist
> in the same git repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-32bit/ubuntu/issues/3#issuecomment-106698122>.
>



-- 
Cheers,
Andrew
